use_frameworks!

target 'ATHMultiSelectionSegmentedControl_Example' do
  pod 'ATHMultiSelectionSegmentedControl', :path => '../'
end

target 'ATHMultiSelectionSegmentedControl_Tests' do
    inherit! :search_paths
    pod 'ATHMultiSelectionSegmentedControl', :path => '../'
    pod 'Nimble'
end

